// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: doshbank_backend/doshbank.proto

package doshbank_backend

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCurrentRewardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCurrentRewardRequest) Reset() {
	*x = GetCurrentRewardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doshbank_backend_doshbank_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCurrentRewardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentRewardRequest) ProtoMessage() {}

func (x *GetCurrentRewardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doshbank_backend_doshbank_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentRewardRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentRewardRequest) Descriptor() ([]byte, []int) {
	return file_doshbank_backend_doshbank_proto_rawDescGZIP(), []int{0}
}

type GetCurrentRewardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reward int32 `protobuf:"varint,1,opt,name=Reward,proto3" json:"Reward,omitempty"`
}

func (x *GetCurrentRewardResponse) Reset() {
	*x = GetCurrentRewardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doshbank_backend_doshbank_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCurrentRewardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentRewardResponse) ProtoMessage() {}

func (x *GetCurrentRewardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doshbank_backend_doshbank_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentRewardResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentRewardResponse) Descriptor() ([]byte, []int) {
	return file_doshbank_backend_doshbank_proto_rawDescGZIP(), []int{1}
}

func (x *GetCurrentRewardResponse) GetReward() int32 {
	if x != nil {
		return x.Reward
	}
	return 0
}

var File_doshbank_backend_doshbank_proto protoreflect.FileDescriptor

var file_doshbank_backend_doshbank_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x64, 0x6f, 0x73, 0x68, 0x62, 0x61, 0x6e, 0x6b, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x65,
	0x6e, 0x64, 0x2f, 0x64, 0x6f, 0x73, 0x68, 0x62, 0x61, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x10, 0x64, 0x6f, 0x73, 0x68, 0x62, 0x61, 0x6e, 0x6b, 0x5f, 0x62, 0x61, 0x63, 0x6b,
	0x65, 0x6e, 0x64, 0x22, 0x19, 0x0a, 0x17, 0x67, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x32,
	0x0a, 0x18, 0x67, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x52, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x32, 0x75, 0x0a, 0x08, 0x44, 0x6f, 0x73, 0x68, 0x42, 0x61, 0x6e, 0x6b, 0x12, 0x69,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x12, 0x29, 0x2e, 0x64, 0x6f, 0x73, 0x68, 0x62, 0x61, 0x6e, 0x6b, 0x5f, 0x62, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x67, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e,
	0x64, 0x6f, 0x73, 0x68, 0x62, 0x61, 0x6e, 0x6b, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x2e, 0x67, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x13, 0x5a, 0x11, 0x64, 0x6f, 0x73,
	0x68, 0x62, 0x61, 0x6e, 0x6b, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_doshbank_backend_doshbank_proto_rawDescOnce sync.Once
	file_doshbank_backend_doshbank_proto_rawDescData = file_doshbank_backend_doshbank_proto_rawDesc
)

func file_doshbank_backend_doshbank_proto_rawDescGZIP() []byte {
	file_doshbank_backend_doshbank_proto_rawDescOnce.Do(func() {
		file_doshbank_backend_doshbank_proto_rawDescData = protoimpl.X.CompressGZIP(file_doshbank_backend_doshbank_proto_rawDescData)
	})
	return file_doshbank_backend_doshbank_proto_rawDescData
}

var file_doshbank_backend_doshbank_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_doshbank_backend_doshbank_proto_goTypes = []interface{}{
	(*GetCurrentRewardRequest)(nil),  // 0: doshbank_backend.getCurrentRewardRequest
	(*GetCurrentRewardResponse)(nil), // 1: doshbank_backend.getCurrentRewardResponse
}
var file_doshbank_backend_doshbank_proto_depIdxs = []int32{
	0, // 0: doshbank_backend.DoshBank.GetCurrentReward:input_type -> doshbank_backend.getCurrentRewardRequest
	1, // 1: doshbank_backend.DoshBank.GetCurrentReward:output_type -> doshbank_backend.getCurrentRewardResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_doshbank_backend_doshbank_proto_init() }
func file_doshbank_backend_doshbank_proto_init() {
	if File_doshbank_backend_doshbank_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_doshbank_backend_doshbank_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCurrentRewardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doshbank_backend_doshbank_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCurrentRewardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_doshbank_backend_doshbank_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_doshbank_backend_doshbank_proto_goTypes,
		DependencyIndexes: file_doshbank_backend_doshbank_proto_depIdxs,
		MessageInfos:      file_doshbank_backend_doshbank_proto_msgTypes,
	}.Build()
	File_doshbank_backend_doshbank_proto = out.File
	file_doshbank_backend_doshbank_proto_rawDesc = nil
	file_doshbank_backend_doshbank_proto_goTypes = nil
	file_doshbank_backend_doshbank_proto_depIdxs = nil
}
