// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: stratagems/stratagems.proto

package stratagems

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelldiverRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	At int32  `protobuf:"varint,2,opt,name=at,proto3" json:"at,omitempty"`
	Mp int32  `protobuf:"varint,3,opt,name=mp,proto3" json:"mp,omitempty"`
}

func (x *HelldiverRequest) Reset() {
	*x = HelldiverRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stratagems_stratagems_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelldiverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelldiverRequest) ProtoMessage() {}

func (x *HelldiverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stratagems_stratagems_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelldiverRequest.ProtoReflect.Descriptor instead.
func (*HelldiverRequest) Descriptor() ([]byte, []int) {
	return file_stratagems_stratagems_proto_rawDescGZIP(), []int{0}
}

func (x *HelldiverRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HelldiverRequest) GetAt() int32 {
	if x != nil {
		return x.At
	}
	return 0
}

func (x *HelldiverRequest) GetMp() int32 {
	if x != nil {
		return x.Mp
	}
	return 0
}

type SuperEarthAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *SuperEarthAnswer) Reset() {
	*x = SuperEarthAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stratagems_stratagems_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuperEarthAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuperEarthAnswer) ProtoMessage() {}

func (x *SuperEarthAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_stratagems_stratagems_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuperEarthAnswer.ProtoReflect.Descriptor instead.
func (*SuperEarthAnswer) Descriptor() ([]byte, []int) {
	return file_stratagems_stratagems_proto_rawDescGZIP(), []int{1}
}

func (x *SuperEarthAnswer) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type QuitMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *QuitMessage) Reset() {
	*x = QuitMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stratagems_stratagems_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuitMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitMessage) ProtoMessage() {}

func (x *QuitMessage) ProtoReflect() protoreflect.Message {
	mi := &file_stratagems_stratagems_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitMessage.ProtoReflect.Descriptor instead.
func (*QuitMessage) Descriptor() ([]byte, []int) {
	return file_stratagems_stratagems_proto_rawDescGZIP(), []int{2}
}

func (x *QuitMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_stratagems_stratagems_proto protoreflect.FileDescriptor

var file_stratagems_stratagems_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x73, 0x74, 0x72, 0x61, 0x74, 0x61, 0x67, 0x65, 0x6d, 0x73, 0x2f, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x61, 0x67, 0x65, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x61, 0x67, 0x65, 0x6d, 0x73, 0x22, 0x42, 0x0a, 0x10, 0x48, 0x65, 0x6c,
	0x6c, 0x64, 0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x61, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x6d, 0x70, 0x22, 0x2a, 0x0a,
	0x10, 0x53, 0x75, 0x70, 0x65, 0x72, 0x45, 0x61, 0x72, 0x74, 0x68, 0x41, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x27, 0x0a, 0x0b, 0x51, 0x75, 0x69,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x32, 0x9e, 0x01, 0x0a, 0x11, 0x53, 0x75, 0x70, 0x65, 0x72, 0x45, 0x61, 0x72, 0x74,
	0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x75,
	0x70, 0x70, 0x6c, 0x79, 0x12, 0x1c, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x61, 0x67, 0x65, 0x6d,
	0x73, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x64, 0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x61, 0x67, 0x65, 0x6d, 0x73, 0x2e,
	0x53, 0x75, 0x70, 0x65, 0x72, 0x45, 0x61, 0x72, 0x74, 0x68, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x22, 0x00, 0x12, 0x3f, 0x0a, 0x09, 0x45, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12,
	0x17, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x61, 0x67, 0x65, 0x6d, 0x73, 0x2e, 0x51, 0x75, 0x69,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x17, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x61, 0x67, 0x65, 0x6d, 0x73, 0x2e, 0x51, 0x75, 0x69, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x73, 0x74, 0x72, 0x61, 0x74, 0x61, 0x67, 0x65, 0x6d,
	0x73, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stratagems_stratagems_proto_rawDescOnce sync.Once
	file_stratagems_stratagems_proto_rawDescData = file_stratagems_stratagems_proto_rawDesc
)

func file_stratagems_stratagems_proto_rawDescGZIP() []byte {
	file_stratagems_stratagems_proto_rawDescOnce.Do(func() {
		file_stratagems_stratagems_proto_rawDescData = protoimpl.X.CompressGZIP(file_stratagems_stratagems_proto_rawDescData)
	})
	return file_stratagems_stratagems_proto_rawDescData
}

var file_stratagems_stratagems_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_stratagems_stratagems_proto_goTypes = []interface{}{
	(*HelldiverRequest)(nil), // 0: stratagems.HelldiverRequest
	(*SuperEarthAnswer)(nil), // 1: stratagems.SuperEarthAnswer
	(*QuitMessage)(nil),      // 2: stratagems.QuitMessage
}
var file_stratagems_stratagems_proto_depIdxs = []int32{
	0, // 0: stratagems.SuperEarthService.Resupply:input_type -> stratagems.HelldiverRequest
	2, // 1: stratagems.SuperEarthService.EndServer:input_type -> stratagems.QuitMessage
	1, // 2: stratagems.SuperEarthService.Resupply:output_type -> stratagems.SuperEarthAnswer
	2, // 3: stratagems.SuperEarthService.EndServer:output_type -> stratagems.QuitMessage
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stratagems_stratagems_proto_init() }
func file_stratagems_stratagems_proto_init() {
	if File_stratagems_stratagems_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stratagems_stratagems_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelldiverRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stratagems_stratagems_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuperEarthAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stratagems_stratagems_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuitMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stratagems_stratagems_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stratagems_stratagems_proto_goTypes,
		DependencyIndexes: file_stratagems_stratagems_proto_depIdxs,
		MessageInfos:      file_stratagems_stratagems_proto_msgTypes,
	}.Build()
	File_stratagems_stratagems_proto = out.File
	file_stratagems_stratagems_proto_rawDesc = nil
	file_stratagems_stratagems_proto_goTypes = nil
	file_stratagems_stratagems_proto_depIdxs = nil
}
