all: orden visualizacion ejecutar1 ejecutar2

orden:
	@gcc -o orden orden.c

visualizacion: 
	@gcc -o visualizacion visualizacion.c

ejecutar1:
	@./orden

ejecutar2:
	@./visualizacion

clear:
	rm -f all *.o