// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: datanode_backend/datanode.proto

package datanode_backend

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DatanodeServiceClient is the client API for DatanodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DatanodeServiceClient interface {
	SaveStep(ctx context.Context, in *SaveStepRequest, opts ...grpc.CallOption) (*SaveStepResponse, error)
	GetIdStepts(ctx context.Context, in *GetIdSteptsRequest, opts ...grpc.CallOption) (*GetIdSteptsResponse, error)
}

type datanodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDatanodeServiceClient(cc grpc.ClientConnInterface) DatanodeServiceClient {
	return &datanodeServiceClient{cc}
}

func (c *datanodeServiceClient) SaveStep(ctx context.Context, in *SaveStepRequest, opts ...grpc.CallOption) (*SaveStepResponse, error) {
	out := new(SaveStepResponse)
	err := c.cc.Invoke(ctx, "/datanode_backend.DatanodeService/SaveStep", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datanodeServiceClient) GetIdStepts(ctx context.Context, in *GetIdSteptsRequest, opts ...grpc.CallOption) (*GetIdSteptsResponse, error) {
	out := new(GetIdSteptsResponse)
	err := c.cc.Invoke(ctx, "/datanode_backend.DatanodeService/GetIdStepts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatanodeServiceServer is the server API for DatanodeService service.
// All implementations must embed UnimplementedDatanodeServiceServer
// for forward compatibility
type DatanodeServiceServer interface {
	SaveStep(context.Context, *SaveStepRequest) (*SaveStepResponse, error)
	GetIdStepts(context.Context, *GetIdSteptsRequest) (*GetIdSteptsResponse, error)
	mustEmbedUnimplementedDatanodeServiceServer()
}

// UnimplementedDatanodeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDatanodeServiceServer struct {
}

func (UnimplementedDatanodeServiceServer) SaveStep(context.Context, *SaveStepRequest) (*SaveStepResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveStep not implemented")
}
func (UnimplementedDatanodeServiceServer) GetIdStepts(context.Context, *GetIdSteptsRequest) (*GetIdSteptsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIdStepts not implemented")
}
func (UnimplementedDatanodeServiceServer) mustEmbedUnimplementedDatanodeServiceServer() {}

// UnsafeDatanodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatanodeServiceServer will
// result in compilation errors.
type UnsafeDatanodeServiceServer interface {
	mustEmbedUnimplementedDatanodeServiceServer()
}

func RegisterDatanodeServiceServer(s grpc.ServiceRegistrar, srv DatanodeServiceServer) {
	s.RegisterService(&DatanodeService_ServiceDesc, srv)
}

func _DatanodeService_SaveStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatanodeServiceServer).SaveStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datanode_backend.DatanodeService/SaveStep",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatanodeServiceServer).SaveStep(ctx, req.(*SaveStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatanodeService_GetIdStepts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIdSteptsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatanodeServiceServer).GetIdStepts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datanode_backend.DatanodeService/GetIdStepts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatanodeServiceServer).GetIdStepts(ctx, req.(*GetIdSteptsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DatanodeService_ServiceDesc is the grpc.ServiceDesc for DatanodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DatanodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "datanode_backend.DatanodeService",
	HandlerType: (*DatanodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveStep",
			Handler:    _DatanodeService_SaveStep_Handler,
		},
		{
			MethodName: "GetIdStepts",
			Handler:    _DatanodeService_GetIdStepts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "datanode_backend/datanode.proto",
}
